version: '2'

services:
    db:
        container_name: nour-2-postgis
        image: mdillon/postgis:latest
        restart: always
        env_file:
        - .env
        ports:
        - "5432:5432"
        environment:
            POSTGRES_DB: chat_system
            POSTGRES_USER: appuser
            POSTGRES_PASSWORD: password

    redis:
        container_name: nour-2-redis
        image: redis:4.0-alpine
        command: redis-server

    web:
        container_name: nour-2-rails
        entrypoint: ["./wait-for-it.sh", "db:5432","--", bin/entry]
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
            - .:/myapp
        ports:
            - '3000:3000'
        depends_on:
            - db
        env_file:
            - .env
        environment:
            POSTGRES_DB: chat_system
            POSTGRES_USER: appuser
            POSTGRES_PASSWORD: password
            DB_HOST: db

    sidekiq:
        container_name: nour-2-sidekiq
        entrypoint: ["./wait-for-it.sh", "web:3000","--", bin/entry]
        build: .
        command: bundle exec sidekiq
        depends_on:
            - web
            - redis
        volumes:
            - .:/myapp
        env_file:
            - .env
        environment:
            JOB_WORKER_URL: redis://redis:6379/0
            POSTGRES_DB: chat_system
            POSTGRES_USER: appuser
            POSTGRES_PASSWORD: password
            DB_HOST: db